### PR TITLE
Complete SpaceX Project

### PR DESCRIPTION
**Pull request by blessedjasonmwanza**
## Complete SpaceX Project
In this project, @cwaku  and I (@blessedjasonmwanza), collaborated to consume SpaceX APIs and build a complete commercial web application. Listed hereunder are the learning objectives and tasks completed.
- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write unit tests with React Testing Library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions, and reducers in React.
- Perform a code review for a team member.
- Deploy application on [Heroku](https://spacex-booking.herokuapp.com/)
- Use react Linters and Stylelint to improve and practice industry standards QA

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Invalid submission 

Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has wrong gitflow

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by blessedjasonmwanza** [comment]
> # Invalid submission
> Hi,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has wrong gitflow
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hello @arslanbisharat ,

- Would you mind sharing a contexture explanation to where we might need changes?
- You marked the review as invalid and reduced the number of attempts in our Dashboard

**Review by arslanbisharat — APPROVED** [review]
Hi, 

I would like to apologize for the mistake in my previous review. Usually, the projects should follow Gitflow but when I saw you haven't followed Gitflow, I invalidated the project.

Now after cross check-in everything, I am apologizing for the mistake that has been done and for the inconvenience that may have been caused. 


Your project has been marked Approved. 

Thank you for your understanding.

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by blessedjasonmwanza** [comment]
> 
Hello @arslanbisharat
Thank you a lot for the clarification. We truly appreciate your professional communication post flow of events. 

> HappyCoding 👨🏽‍💻

**Pull request merged**
